### ISSUE TITLE
README wording is hard to understand

### ISSUE THREAD

**Issue by vmallet** [AntoineBlaud/EasyRePlugin#1]
The wording in the README.md file has many issues which makes it pretty hard to understand what the plugin does.

I am sending a PR over to address some issues but there are others parts where I am not sure what was meant.

Here are a few questions I have; feel free to answer in French, I might be able to help with the translation :)

>  It allow in a easy way to compare data given to specific part of the code between different calls.

What do you mean? 

> This functionality aims to hook the function code, but also discover parents.

What do you mean? Why is it "**_but_** also discover parents", and what's a parent?

> **MAX_PARENTS** is the number of parents to discover (considers as a tree)

What do you mean by "considers as a tree"?

> Chirurgical tracing

Two things here:

- What makes this "chirurgical" vs. not? What do you mean by that?
- "Chirurgical" should be "Surgical" but I'm not sure what the intent is here so I didn't change it in the PR.

(Note: discovered this plugin while updating the IDA plugin list I maintain at: http://vmallet.github.io/ida-plugins)

**Comment by AntoineBlaud** [comment]
Thank you for you reply and your time ! I will working on it this night to improve it. 🫡

**Comment by AntoineBlaud** [comment]
Done. Many thanks for the help :)
