### ISSUE TITLE
Improve plugin discoverability

### ISSUE THREAD

**Issue by vmallet** [AntoineBlaud/EasyRePlugin#3]
Couple of suggestions to improve the plugin's discoverability:
- Add a couple of "topics" in the about: ida ida-pro, ida-plugin, idapython maybe?
- Improve the wording of the About text.

Suggestion:

_IDA Python3 Plugin to make your RE life easier. Trace execution and save code/memory for detailed exploration._

**Comment by vmallet** [comment]
Just saw you closed this issue but I don't see the changes. I saw you added tags to the README (that's useful too) but I was talking about updating the "Description" and "Topics" of the GitHub project, i.e. by clicking the gear icon top-right of the GitHub project page (next to "About) and working with the Description and Topics fields. Does that make sense?
(Sadly I can't re-open this issue :) 

The gear icon:
<img width="611" alt="GitHubAboutCog" src="https://user-images.githubusercontent.com/205806/183316879-ceb20311-2677-48be-8069-01d422baf1d0.png">

The Description & Topics fields:
<img width="698" alt="GitHubAboutDialog" src="https://user-images.githubusercontent.com/205806/183316894-05e0d5da-3068-41a2-ae07-00bda57ccba5.png">
)

**Comment by AntoineBlaud** [comment]
Reopen this issue because tags were not well placed.

**Comment by vmallet** [comment]
Looks good now!

**Comment by AntoineBlaud** [comment]
Many Thanks ! :)
